MessageOfTheDay.WebUI/Models/ContextModel.cs
using System.Collections.Generic;
using MessageOfTheDay.Domain.Entities;

namespace MessageOfTheDay.WebUI.Models
{
    public class ContextModel
    {
        public IEnumerable<Day> Days { get; set; }

        public IEnumerable<Language> Languages { get; set; }

        public Message Message { get; set; }

        public string FlagPath { get; set; }
    }
}

MessageOfTheDay.WebUI/Models/ShowDropdownsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MessageOfTheDay.Domain.Entities;

namespace MessageOfTheDay.WebUI.Models
{
    public class ShowDropdownsModel
    {
        private IEnumerable<Day> days;

        private IEnumerable<Language> languages;

        public ShowDropdownsModel(IEnumerable<Day> days, IEnumerable<Language> languages)
        {
            this.days = days;
            this.languages = languages;
        }

        public ShowDropdownsModel()
        {

        }

        public int SelectedDayId = (int)DateTime.Today.DayOfWeek == 0 ? 7 : (int)DateTime.Today.DayOfWeek;
        public int SelectedLanguageId = 1;

        public SelectListItem[] Languages
        {
            get
            {
                return languages.Select(l => new SelectListItem { Text = l.Name, Value = l.Id.ToString() }).ToArray();
            }
        }

        public SelectListItem[] Days
        {
            get
            {
                return days.Select(d => new SelectListItem { Text = d.Name, Value = d.Id.ToString() }).ToArray();
            }
        }
    }
}

MessageOfTheDay.WebUI/Models/UserSelection.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MessageOfTheDay.Domain.Abstract;
using MessageOfTheDay.Domain.Concrete;
using MessageOfTheDay.Domain.Entities;

namespace MessageOfTheDay.WebUI.Models
{
    public class UserSelection
    {
        public int SelectedDayId {get; set;}
        public int SelectedLanguageId { get; set; }
    }
}

MessageOfTheDay.WebUI/Controllers/MessageController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MessageOfTheDay.WebUI.Models;
using MessageOfTheDay.Domain.Abstract;
using MessageOfTheDay.Domain.Entities;

namespace MessageOfTheDay.WebUI.Controllers
{
    public class MessageController : Controller
    {
        private IMessageRepository _messageRepository;
        private ILanguageRepository _languageRepository;
        private IDayRepository _dayRepository;

        public MessageController(IMessageRepository messageRepository, ILanguageRepository languageRepository,
            IDayRepository dayRepository)
        {
            _messageRepository = messageRepository;
            _languageRepository = languageRepository;
            _dayRepository = dayRepository;
        }

        [HttpGet]
        public ActionResult List()
        {
            var todayId = ((int) DateTime.Today.DayOfWeek == 0) ? 7 : (int) DateTime.Today.DayOfWeek;
            var defaultLangId = 1;
            var model = new ContextModel()
            {
                Languages = _languageRepository.LanguagesEnumerable,
                Days = _dayRepository.DaysEnumerable,
                Message =
                    _messageRepository.MessagesEnumerable.Single(
                        m => m.DayId == todayId && m.LanguageId == defaultLangId),
                FlagPath = GetImagePath(defaultLangId)
            };

            return View(model);
        }

        [HttpPost]
        public ViewResult List(UserSelection userSelection)
        {
            var model = new ContextModel()
            {
                Languages = _languageRepository.LanguagesEnumerable,
                Days = _dayRepository.DaysEnumerable,
                Message =
                    _messageRepository.MessagesEnumerable.Single(
                        m => m.DayId == userSelection.SelectedDayId && m.LanguageId == userSelection.SelectedLanguageId),
                FlagPath = GetImagePath(userSelection.SelectedLanguageId)
            };

            return View(model);
        }

        public string GetImagePath(int langId)
        {
            var language = _languageRepository.LanguagesEnumerable
                .FirstOrDefault(l => l.Id == langId);
            if (language != null)
            {
                return language.PartialFlagPath;
            }
            else
            {
                return null;
            }
        }

        [HttpPost]
        public void Save(Message message)
        {
            _messageRepository.SaveMessage(message);
        }
    }
}

MessageOfTheDay.WebUI/Views/Message/List.cshtml
@model MessageOfTheDay.WebUI.Models.ContextModel
@{
    ViewBag.Title = "Message of the Day";
}
<div>

    @using (Ajax.BeginForm("Save", "Message", new AjaxOptions() {}))
    {
        @Html.Label("This is a message of " + @Model.Days.Single(m => m.Id == Model.Message.DayId).Name) <br/>
        @Html.TextAreaFor(m => m.Message.TodaysMessage)
        @Html.HiddenFor(m => m.Message.Id)
        <input type = "submit" value="Save"><br>
        }
    </div>

<img src="@Url.Content("~/Content/Images/" + Model.FlagPath)" />

    @Html.Partial("ShowDropdowns", new MessageOfTheDay.WebUI.Models.ShowDropdownsModel(Model.Days, Model.Languages))

MessageOfTheDay.WebUI/Views/Message/ShowDropdowns.cshtml
@model MessageOfTheDay.WebUI.Models.ShowDropdownsModel

@using (Html.BeginForm("List", "Message", FormMethod.Post))
{
    <fieldset>
        <span>
            @Html.DropDownListFor(s => s.SelectedLanguageId, Model.Languages)
        </span>
        <span>
            @Html.DropDownListFor(d => d.SelectedDayId, Model.Days)
        </span>
        <input type="submit" value="Show the message!" />
    </fieldset>
}

MessageOfTheDay.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet"/>

    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    <title>@ViewBag.Title - My ASP.NET Application</title>
    
</head>
<body>
<div class="row panel">
    <div id="dayIDs" class="col-xs-3">
    </div>
    <div class="col-xs-8">
        @RenderBody()
    </div>

</div>
   <script>alert("reloaded");</script>
</body>
</html>